# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7179fda56925c37a5dbdd61ee923a45b22de357064d69d781795d6e247ac51c6baf8bde9831e3df17a2c4d83c088078f1fc4d0ce72eb1eddb67a6359874d5e62

test:
  secret_key_base: 3796e1c31b45b228a13859358bce9ddc01eed768a5aa1465c7cebdc4981fabc0e04b14f7de9625016f7aa86930b8eb85b1e229a6791047d3f8f097df74dae793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>